// Generated by CoffeeScript 1.11.1
(function() {
  var QUESTION_VALUES, request, urls;

  urls = require('./urls');

  request = require('request');

  QUESTION_VALUES = {
    24: 2,
    16: 2,
    25: 2,
    14: 1,
    17: 4,
    19: 2,
    21: 2,
    22: 1,
    20: 1
  };

  module.exports = function(arg) {
    var id, name;
    id = arg.id, name = arg.name;
    return new Promise(function(resolve, reject) {
      return request.post(urls.section, {
        form: {
          lectureID: id
        },
        json: true
      }, function(err, response, rawSection) {
        var questions, rawQuestion;
        if (err != null) {
          reject(err);
          return;
        }
        if (response.statusCode !== 200) {
          reject(new Error('Invalid status code returned while retrieving section: ' + response.statusCode));
          return;
        }
        questions = (function() {
          var i, len, ref, results;
          ref = rawSection.Questions;
          results = [];
          for (i = 0, len = ref.length; i < len; i++) {
            rawQuestion = ref[i];
            results.push({
              id: rawQuestion.QuestionID,
              correctAnswers: rawQuestion.CorrectAnswers,
              value: QUESTION_VALUES[id] || 0
            });
          }
          return results;
        })();
        return resolve({
          id: id,
          name: name,
          questions: questions
        });
      });
    });
  };

}).call(this);

//# sourceMappingURL=fetchSection.js.map
