// Generated by CoffeeScript 1.11.1
(function() {
  var HOSTNAME;

  HOSTNAME = 'http://etesty2.mdcr.cz';

  module.exports = {
    hostname: HOSTNAME,
    sectionList: HOSTNAME + '/Home/Tests/',
    SECTION: HOSTNAME + '/Test/GeneratePractise/',
    questionPage: HOSTNAME + '/Vestnik/ShowPartial'
  };

}).call(this);

//# sourceMappingURL=urls.js.map
