// Generated by CoffeeScript 1.11.1
(function() {
  var LessPluginAutoPrefix, PATHS, fs, less, lessSrc, path, sourcePath, targetPath;

  PATHS = require('./../PATHS');

  path = require('path');

  fs = require('fs-extra');

  less = require('less');

  LessPluginAutoPrefix = require('less-plugin-autoprefix');

  sourcePath = path.resolve(PATHS.CLIENT, './res/less/index.less');

  targetPath = path.resolve(PATHS.CLIENT, './res/css/index.css');

  lessSrc = fs.readFileSync(sourcePath, 'utf8');

  less.render(lessSrc, {
    plugins: [
      new LessPluginAutoPrefix({
        browsers: '>1%'
      })
    ],
    filename: sourcePath
  })["catch"](function(err) {
    console.error('ERROR OCCURRED WHILE COMPILING LESS STYLESHEETS');
    console.error(err);
    return process.exit(1);
  }).then(function(output) {
    fs.outputFileSync(targetPath, output.css);
    return console.log('CSS BUNDLE SUCCESSFULLY BUILT');
  });

}).call(this);

//# sourceMappingURL=index.js.map
