// Generated by CoffeeScript 1.11.1
(function() {
  var DEFAULT_HISTORY_PATH, TEST_ROOT_DIR, executeTest, humanifyOutput, path, processTestResult, readTestHistory, stringifyOutput, writeTestHistory;

  TEST_ROOT_DIR = path.resolve(__dirname, '..');

  DEFAULT_HISTORY_PATH = path.resolve(TEST_ROOT_DIR, './history.json');

  path = require('path');

  executeTest = require('./test/execute');

  processTestResult = require('./process/wrapper');

  readTestHistory = require('./history/read');

  writeTestHistory = require('./history/write');

  humanifyOutput = require('./output/humanify');

  stringifyOutput = require('./output/stringify');

  module.exports = function(testerDirPath, targetDirPath, historyPath) {
    var historyPromise, resultPromise;
    if (historyPath == null) {
      historyPath = DEFAULT_HISTORY_PATH;
    }
    resultPromise = executeTest(testerDirPath, targetDirPath);
    historyPromise = readTestHistory(historyPath);
    return processTestResult(resultPromise, historyPromise).then(humanifyOutput).then(function(testOutput) {
      testOutput.writePromise = writeTestHistory(historyPath, testOutput.raw);
      delete testOutput.raw;
      return testOutput;
    }).then(stringifyOutput).then(function(textOutput) {
      return console.log(textOutput);
    }, function(error) {
      return console.log(error.stack);
    });
  };

}).call(this);

//# sourceMappingURL=index.js.map
