// Generated by CoffeeScript 1.11.1
(function() {
  var Promise, fs;

  fs = require('fs');

  Promise = require('promise');

  module.exports = {
    read: Promise.denodeify(fs.readFile),
    write: Promise.denodeify(fs.writeFile),
    exists: function(path) {
      return new Promise(function(fulfill, reject) {
        return fs.exists(path, function(exists) {
          if (exists) {
            return fulfill();
          } else {
            return reject();
          }
        });
      });
    }
  };

}).call(this);

//# sourceMappingURL=promisifiedFs.js.map
