// Generated by CoffeeScript 1.11.1
(function() {
  var chalk;

  chalk = require('chalk');

  module.exports = function(err, stats) {
    var json;
    if (err != null) {
      console.error(chalk.redBright('ERROR OCCURRED WHILE COMPILING CLIENT'));
      console.error(chalk.redBright(err.stack || err));
      if (err.details != null) {
        console.error(chalk.redBright(err.details));
      }
      return 1;
    }
    json = stats.toJson({
      errors: true,
      warnings: true
    });
    if (stats.hasErrors()) {
      console.error(chalk.redBright(json.errors));
      return 1;
    }
    if (stats.hasWarnings()) {
      console.warn(chalk.yellowBright('WARNINGS:'));
      console.warn(chalk.yellowBright(json));
      return 0;
    }
    console.log(stats.toString('normal'));
    console.log(chalk.green('SUCCESSFULLY COMPILED'));
    return 0;
  };

}).call(this);

//# sourceMappingURL=compileCb.js.map
