// Generated by CoffeeScript 1.11.1
(function() {
  var compileCb, getConfig, webpack;

  webpack = require('webpack');

  compileCb = require('./compileCb');

  getConfig = require('./webpack.config');

  webpack(getConfig(), function(err, stats) {
    var outputCode;
    outputCode = compileCb(err, stats);
    return process.exit(outputCode);
  });

}).call(this);

//# sourceMappingURL=index.js.map
