// Generated by CoffeeScript 1.11.1
(function() {
  var compileCb, compiler, getConfig, webpack;

  webpack = require('webpack');

  compileCb = require('./compileCb');

  getConfig = require('./webpack.config');

  compiler = webpack(getConfig());

  compiler.watch({}, function(err, stats) {
    compileCb(err, stats);
  });

}).call(this);

//# sourceMappingURL=watchCoffee.js.map
