// Generated by CoffeeScript 1.12.6
(function() {
  var jsdom, urls;

  urls = require('./../urls');

  jsdom = require('jsdom');

  module.exports = function() {
    return new Promise(function(resolve, reject) {
      return jsdom.env(urls.sectionList, function(err, window) {
        var sectionList;
        if (err != null) {
          reject(err);
          return;
        }
        sectionList = Array.from(window.document.getElementsByClassName('VerticalMenu')[0].children).map(function(el) {
          var href, id, sectionName;
          href = el.children[0].href;
          id = parseInt(href.substr(href.lastIndexOf('/') + 1));
          sectionName = el.children[0].innerHTML;
          return {
            id: id,
            name: sectionName
          };
        });
        return resolve(sectionList);
      });
    });
  };

}).call(this);

//# sourceMappingURL=fetchSectionList.js.map
