// Generated by CoffeeScript 1.11.1
(function() {
  var etag, fs, getSinceParam, getWithRemoteImgParam, logger;

  fs = require('fs');

  etag = require('etag');

  logger = global.logger.getChildLogger('webserver/api');

  getWithRemoteImgParam = function(req) {
    var withRemoteImg;
    withRemoteImg = req.query.withRemoteImg;
    if (withRemoteImg != null) {
      if (withRemoteImg === 'true') {
        return true;
      } else if (withRemoteImg === 'false') {
        return false;
      } else {
        return null;
      }
    }
    return false;
  };

  getSinceParam = function(req) {
    var since, sinceStr;
    sinceStr = req.query.since;
    if (sinceStr == null) {
      return -2e308;
    }
    since = parseInt(req.query.since);
    if (isNaN(since)) {
      return null;
    } else {
      return since;
    }
  };

  module.exports = function(req, res, next, store) {
    var collection, i, id, ids, len, path, pathArr, responseStr, result, resultLength, since, withRemoteImg;
    pathArr = req.path.split('/').slice(1);
    if (pathArr.length === 1 || (pathArr.length === 2 && pathArr[1] === '')) {
      res.sendFile(__dirname + '/apiHelp.txt');
      return;
    }
    path = pathArr.slice(1).join('/');
    if (req.query.id != null) {
      ids = req.query.id.split(',').map(function(str) {
        return parseInt(str.trim(), 10);
      }).filter(function(n) {
        return !isNaN(n);
      });
    } else {
      ids = null;
    }
    logger.log('idParsed', 'ID query parsed', {
      reqId: req.id,
      parsedIds: ids
    });
    switch (path) {
      case 'getSection':
      case 'getSection/':
        collection = store.sections;
        break;
      case 'getQuestion':
      case 'getQuestion/':
        withRemoteImg = getWithRemoteImgParam(req);
        switch (withRemoteImg) {
          case true:
            collection = store.remoteImgQuestions;
            break;
          case false:
            collection = store.localImgQuestions;
            break;
          case null:
            res.status(400).send('Invalid value of "withRemoteImg" parameter - must be either "true" or "false"');
            return;
        }
        break;
      default:
        logger.log('endpointResolved', 'Invalid endpoint: `' + path + '`', {
          reqId: req.id,
          apiEndpoint: path,
          validEndpoint: false
        });
        next();
        return;
    }
    logger.log('endpointResolved', 'Requesting `' + path + '`', {
      reqId: req.id,
      apiEndpoint: path,
      validEndpoint: true
    });
    if ((ids != null) && ids.length === 0) {
      logger.log('incorrectQueryFormat', 'Request had incorrect query ID format: `' + req.query.id + '`', {
        reqId: req.id,
        idQuery: req.query.id
      });
      res.sendStatus(400);
      return;
    }
    since = getSinceParam(req);
    if (since == null) {
      res.status(400).send('Invalid value of "since" parameter - must be integer timestamp');
      return;
    }
    if (collection.lastChange <= since) {
      res.sendStatus(304);
      return;
    }
    if (ids == null) {
      result = collection.get();
    } else if (ids.length === 1) {
      result = collection.get(ids[0]);
    } else {
      result = [];
      for (i = 0, len = ids.length; i < len; i++) {
        id = ids[i];
        result.push(collection.get(id));
      }
    }
    if (Array.isArray(result)) {
      resultLength = result.length;
    } else {
      resultLength = 1;
    }
    logger.log('resultRetrieved', 'Retrieved result: ' + resultLength + ' items', {
      reqId: req.id,
      resultLength: resultLength
    });
    responseStr = JSON.stringify(result);
    res.setHeader('Content-Type', 'application/json');
    res.setHeader('Last-Modified', new Date(collection.lastChange * 1000).toUTCString());
    res.setHeader('ETag', etag(responseStr));
    return res.send(responseStr);
  };

}).call(this);

//# sourceMappingURL=handleApiCall.js.map
