// Generated by CoffeeScript 1.12.6
(function() {
  var alreadyRunning, cors, express, handleApiCall, limitToGetMw, logger, path;

  path = require('path');

  express = require('express');

  cors = require('cors');

  handleApiCall = require('./handleApiCall');

  logger = global.logger.getChildLogger('webserver');

  alreadyRunning = false;

  limitToGetMw = function(req, res, next) {
    if (req.method.toLowerCase() !== 'get') {
      res.status(405);
      res.setHeader('Allow', 'GET');
      return res.send('Only `GET` HTTP method is allowed!');
    } else {
      return next();
    }
  };

  module.exports = function(store, staticDirPath, testImgDirPath, port) {
    var listener, webserver;
    if (alreadyRunning) {
      logger.error('alreadyRunning', 'Webserver instance is already running!');
      throw new Error('Webserver instance is already running!');
    }
    alreadyRunning = true;
    webserver = express();
    webserver.all('/api*', cors());
    webserver.all('/api*', limitToGetMw);
    webserver.get('/api*', function(req, res, next) {
      return handleApiCall(req, res, next, store);
    });
    webserver.all('/questionImg*', cors());
    webserver.all('/questionImg*', limitToGetMw);
    webserver.use('/questionImg', express["static"](testImgDirPath));
    webserver.use(express["static"](staticDirPath));
    webserver.use(function(err, req, res, next) {
      res.sendStatus(500);
      return logger.error('error', 'Error occurred in webserver!', err);
    });
    return listener = webserver.listen(port, function() {
      port = listener.address().port;
      logger.log('start', 'Webserver started!', {
        port: port
      });
      return console.log('Webserver running on port ' + port);
    });
  };

}).call(this);

//# sourceMappingURL=startWebserver.js.map
