// Generated by CoffeeScript 1.11.1
(function() {
  var alreadyRunning, cors, express, handleApiCall, logger, path;

  path = require('path');

  express = require('express');

  cors = require('cors');

  handleApiCall = require('./handleApiCall');

  logger = global.logger.getChildLogger('webserver');

  alreadyRunning = false;

  module.exports = function(store, staticDirPath, port) {
    var listener, webserver;
    if (alreadyRunning) {
      logger.error('alreadyRunning', 'Webserver instance is already running!');
      throw new Error('Webserver instance is already running!');
    }
    alreadyRunning = true;
    webserver = express();
    webserver.all('/api*', cors());
    webserver.get('/api*', function(req, res, next) {
      return handleApiCall(req, res, next, store);
    });
    webserver.all('/api*', function(req, res, next) {
      if (req.method.toLowerCase() !== 'get') {
        return res.send('Only `GET` HTTP method is allowed!');
      } else {
        return next();
      }
    });
    webserver.use(express["static"](staticDirPath));
    webserver.use(function(err, req, res, next) {
      res.sendStatus(500);
      return logger.error('error', 'Error occurred in webserver!', err);
    });
    return listener = webserver.listen(port, function() {
      return logger.log('start', 'Webserver started!', {
        port: listener.address().port
      });
    });
  };

}).call(this);

//# sourceMappingURL=startWebserver.js.map
