// Generated by CoffeeScript 1.11.1
(function() {
  var path;

  path = require('path');

  module.exports = {
    port: 8080,
    dataStoreDirPath: path.resolve(__dirname, '../data/testData/'),
    logFilePath: path.resolve(__dirname, '../data/logs.txt'),
    staticDir: path.resolve(__dirname, '../client/')
  };

}).call(this);

//# sourceMappingURL=config.js.map
