// Generated by CoffeeScript 1.11.1
(function() {
  var Logger, PORT, TestDataStore, config, startWebserver, store;

  config = require('./config');

  Logger = require('./logger');

  global.logger = new Logger(config.logFilePath);

  TestDataStore = require('./TestDataStore');

  startWebserver = require('./webserver/startWebserver');

  global.logger.log('Starting new server instance');

  PORT = process.env.PORT || config.port;

  store = new TestDataStore(config.testDataPaths);

  startWebserver(store, config.staticDir, config.testDataPaths.imgDir, PORT);

}).call(this);

//# sourceMappingURL=index.js.map
