// Generated by CoffeeScript 1.11.1
(function() {
  var ReadOnlyCollection, TestDataStore, config, fs, logger, path,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  path = require('path');

  fs = require('fs');

  config = require('./config');

  ReadOnlyCollection = require('./ReadOnlyCollection');

  logger = global.logger.getChildLogger('testDataStore');

  module.exports = TestDataStore = (function() {
    function TestDataStore(paths) {
      this._loadRemoteImgQuestions = bind(this._loadRemoteImgQuestions, this);
      this._loadLocalImgQuestions = bind(this._loadLocalImgQuestions, this);
      this._loadSections = bind(this._loadSections, this);
      this._loadSections(paths.sections);
      this._watchResource(paths.sections, this._loadSections);
      this._loadLocalImgQuestions(paths.localImgQuestions);
      this._watchResource(paths.localImgQuestions, this._loadLocalImgQuestions);
      this._loadRemoteImgQuestions(paths.remoteImgQuestions);
      this._watchResource(paths.remoteImgQuestions, this._loadRemoteImgQuestions);
      logger.log('Test data loaded');
    }

    TestDataStore.prototype._loadSections = function(sectionFilePath, reload) {
      if (reload == null) {
        reload = false;
      }
      this.sections = this._loadTestDataPart(sectionFilePath);
      return logger.log('Sections ' + (reload ? 're' : '') + 'loaded', this.sections.length);
    };

    TestDataStore.prototype._loadLocalImgQuestions = function(questionFilePath, reload) {
      if (reload == null) {
        reload = false;
      }
      this.localImgQuestions = this._loadTestDataPart(questionFilePath);
      return logger.log('Local img questions ' + (reload ? 're' : '') + 'loaded', this.localImgQuestions.length);
    };

    TestDataStore.prototype._loadRemoteImgQuestions = function(questionFilePath, reload) {
      if (reload == null) {
        reload = false;
      }
      this.remoteImgQuestions = this._loadTestDataPart(questionFilePath);
      return logger.log('Remote img questions ' + (reload ? 're' : '') + 'loaded', this.remoteImgQuestions.length);
    };

    TestDataStore.prototype._watchResource = function(filePath, callback) {
      return fs.watch(filePath, function() {
        return callback(filePath, true);
      });
    };

    TestDataStore.prototype._loadTestDataPart = function(filePath) {
      var lastChangeStr, testDataStr;
      try {
        testDataStr = fs.readFileSync(filePath);
        lastChangeStr = fs.readFileSync(filePath + config.collectionSuffix.lastChange);
        return new ReadOnlyCollection(JSON.parse(testDataStr), parseInt(lastChangeStr));
      } catch (error) {
        logger.log('No valid file found at ' + filePath, {
          filePath: filePath
        });
        return new ReadOnlyCollection([], 0);
      }
    };

    return TestDataStore;

  })();

}).call(this);

//# sourceMappingURL=TestDataStore.js.map
