metaSymbol = require('../../METADATA_SYMBOL')

module.exports = (item) ->
	if item == null
		throw new TypeError('item must be object, not null')
	if typeof item != 'object'
		throw new TypeError('item must be object, not ' + typeof item)
	if !item[metaSymbol]?
		console.log(item)
		throw new TypeError('item is not eveStore item - you must only pass item object generated by eveStore')
	return true