// Generated by CoffeeScript 1.11.1
(function() {
  var chalk, fs, getProcessedQuestions, getProcessedSections, loadRawQuestions, loadRawSections, path, saveCollection;

  path = require('path');

  fs = require('fs');

  chalk = require('chalk');

  loadRawSections = require('./loadRawSections');

  loadRawQuestions = require('./loadRawQuestions');

  getProcessedSections = require('./getProcessedSections');

  getProcessedQuestions = require('./getProcessedQuestions');

  saveCollection = require('./../util/saveCollection');

  module.exports = function(sectionFilePath, questionFilePath) {
    return loadRawSections().then(function(rawSections) {
      return Promise.all([rawSections, loadRawQuestions()]);
    }).then(function(arg) {
      var questions, questionsChanged, rawQuestions, rawSections, sections, sectionsChanged;
      rawSections = arg[0], rawQuestions = arg[1];
      sections = getProcessedSections(rawQuestions, rawSections);
      questions = getProcessedQuestions(rawQuestions, rawSections);
      sectionsChanged = saveCollection(sectionFilePath, sections, 'sections');
      questionsChanged = saveCollection(questionFilePath, questions, 'remote image questions');
      console.log('');
      console.log(chalk.magenta('UPDATE FINISHED:'));
      console.log(chalk.magenta('	sections were updated: ' + sectionsChanged.toString().toUpperCase()));
      console.log(chalk.magenta('	questions were updated: ' + questionsChanged.toString().toUpperCase()));
      return console.log('');
    });
  };

}).call(this);

//# sourceMappingURL=index.js.map
