// Generated by CoffeeScript 1.8.0
(function() {
  var MESSAGES, file;

  file = require('../promisifiedFs');

  MESSAGES = {
    badJson: 'Could not parse the history JSON'
  };

  module.exports = function(historyFilePath) {
    return file.exists(historyFilePath).then(function() {
      return file.read(historyFilePath);
    }).then(function(rawHistory) {
      try {
        return JSON.parse(rawHistory);
      } catch (_error) {
        throw new Error(MESSAGES.badJson);
      }
    }, function() {
      return [];
    }).then(function(history) {
      var fileLog, last, lastLogHistory, _i, _len;
      lastLogHistory = {};
      for (_i = 0, _len = history.length; _i < _len; _i++) {
        fileLog = history[_i];
        last = fileLog.data[fileLog.data.length - 1];
        if (last !== void 0) {
          lastLogHistory[fileLog.file] = last;
        }
      }
      return {
        last: lastLogHistory,
        raw: history
      };
    });
  };

}).call(this);
