// Generated by CoffeeScript 1.11.1
(function() {
  var MESSAGES, file;

  file = require('../promisifiedFs');

  MESSAGES = {
    error: 'Could not save the history file: '
  };

  module.exports = function(filePath, data) {
    return file.write(filePath, JSON.stringify(data)).then(null, function(error) {
      throw new Error(MESSAGES.error + error.stack);
    });
  };

}).call(this);

//# sourceMappingURL=write.js.map
