// Generated by CoffeeScript 1.11.1
(function() {
  var browserify, bundle, coffeeify, fs, minifyify, path, paths;

  browserify = require('browserify');

  coffeeify = require('coffeeify');

  minifyify = require('minifyify');

  path = require('path');

  fs = require('fs-extra');

  paths = {
    src: path.resolve('../client/res/coffee/index.coffee'),
    out: path.resolve('../client/res/js/bundle.js')
  };

  bundle = browserify({
    extensions: ['.coffee'],
    debug: true
  });

  bundle.transform(coffeeify);

  bundle.add(paths.src);

  bundle.bundle(function(err, buffer) {
    if (err) {
      throw err;
    }
    fs.outputFileSync(paths.out, buffer);
    return console.log('SUCCESSFULLY COMPILED TO ' + paths.out);
  });

}).call(this);

//# sourceMappingURL=compileCoffee.js.map
