// Generated by CoffeeScript 1.8.0
(function() {
  var Promise, processTest;

  Promise = require('promise');

  processTest = require('./process');

  module.exports = function(resultPromise, historyPromise) {
    return Promise.all([resultPromise, historyPromise]).then(function(resultArr) {
      var history, rawHistory, result, testResults;
      testResults = resultArr[0];
      history = resultArr[1].last;
      rawHistory = resultArr[1].raw;
      result = processTest(testResults, history, rawHistory);
      return {
        raw: rawHistory,
        result: result
      };
    });
  };

}).call(this);
